AT user category topic feature
Dutus244/TKPM-Project pull request #21
Opened 2023-04-14 15:26 UTC by annthu872

2023-04-15 10:23 UTC, mugetsu0422 requested changes

2023-04-15 10:23 UTC, mugetsu0422 commented on routes/learner.route.js
> +    console.log(total)
xóa log

2023-04-15 10:23 UTC, mugetsu0422 commented on routes/learner.route.js
> +    console.log(list)
xóa log

2023-04-15 10:23 UTC, mugetsu0422 commented on routes/learner.route.js
> +    console.log(total)
xóa log

2023-04-15 10:23 UTC, mugetsu0422 commented on routes/learner.route.js
> +    console.log(list)
xóa log

2023-04-15 10:23 UTC, mugetsu0422 commented on services/learner.service.js
>      return db.raw('select topics.* ,(select count(*)\n' +
\n ko cần thiết lắm

2023-04-15 12:06 UTC, quytrungg commented on public/css/vwLearner/category.css
> +.btn{
mỗi css có 1 dòng trống ở giữa thì sẽ đẹp hơn :Đ

2023-04-15 12:07 UTC, quytrungg commented on routes/learner.route.js
>    const temp = await learnerService.findAllTopicStudy('c2229cc2-cbe1-11ed-b9d3-002248eb7c8a');
sao chỗ này gán cứng giá trị `c2229cc2-cbe1-11ed-b9d3-002248eb7c8a` z :D

2023-04-15 12:07 UTC, quytrungg commented on routes/learner.route.js
> +  const category_id = req.params.category_id;
```suggestion
  const {category_id} = req.params;
```

2023-04-15 12:08 UTC, quytrungg commented on routes/learner.route.js
> +  const temp = await learnerService.findAllTopicStudy(category_id);
đặt tên biến là `temp`???

2023-04-15 12:08 UTC, quytrungg commented on routes/learner.route.js
> +    const limit = 6;
hong nên gán cứng như này

2023-04-15 12:15 UTC, quytrungg commented on services/learner.service.js
> +    var sql = await db('categories').where('IsDelete',0).count({count: '*'}).first();
chỗ này có cần phải dùng `var` hong

2023-04-15 12:18 UTC, quytrungg commented on routes/learner.route.js
> +    }
Logic khúc này giống với dòng 139->152, có thể viết 1 hàm trung gian kiểu như `function setup_pages(...)`

2023-04-15 12:19 UTC, quytrungg requested changes
💯

2023-04-15 12:19 UTC, quytrungg commented on services/learner.service.js
>      return db.raw('select topics.* ,(select count(*)\n' +
bỏ vào `\n` nè ông

2023-04-15 12:27 UTC, annthu872 commented on services/learner.service.js
>      return db.raw('select topics.* ,(select count(*)\n' +
tại tui copy từ sql sang nên nó có \n, mà ddeer vầy cho nó xuống dòng dễ nhìn nhỉ :<

2023-04-15 12:29 UTC, mugetsu0422 commented on services/learner.service.js
>      return db.raw('select topics.* ,(select count(*)\n' +
r dễ nhìn dữ chưa, b đã xuống dòng trong code r mà, xuống dòng trong chuỗi chi :(

2023-04-15 12:30 UTC, annthu872 commented on routes/learner.route.js
>    const temp = await learnerService.findAllTopicStudy('c2229cc2-cbe1-11ed-b9d3-002248eb7c8a');
tại bình thường sẽ có user đăng nhập thì tui lấy id user lun mà nhóm chưa làm cái đó nên tui để 1 id user cho nó có hiện được dữ liệu ấy

2023-04-15 17:48 UTC, quytrungg approved these changes

2023-04-16 13:39 UTC, mugetsu0422 approved these changes

2023-04-16 13:42 UTC, merged