ND: feature daily test
Dutus244/TKPM-Project pull request #23
Opened 2023-04-16 17:28 UTC by Dutus244

2023-04-17 05:16 UTC, mugetsu0422 requested changes

2023-04-17 05:16 UTC, mugetsu0422 commented on package.json
> +    "bootstrap-icons": "^1.10.4",
có gắn link bootstrap icon r mà sao còn npm bootstrap icon v ô :(

2023-04-17 05:16 UTC, mugetsu0422 commented on routes/learner.route.js
> +    userid: "6a6e7163-c669-480c-a28a-980246b50b98",
có login r thì đừng gán cứng nữa ô

2023-04-17 05:16 UTC, mugetsu0422 commented on routes/learner.route.js
> +  const userID = '6a6e7163-c669-480c-a28a-980246b50b98'
này cũng v

2023-04-17 05:16 UTC, mugetsu0422 commented on services/learner.service.js
> +function shuffleArray(array) {
ô có thể bỏ hàm này qua helper.js để reuse

2023-04-17 05:16 UTC, mugetsu0422 commented on services/learner.service.js
> +            // const randomType1 = Math.floor(Math.random() * 3);
ko dùng nữa thì xóa đi ô

2023-04-17 05:16 UTC, mugetsu0422 commented on views/vwLearner/dailyTest.hbs
> +<!--<!DOCTYPE html>-->
ko dùng thì xóa ô

2023-04-17 05:16 UTC, mugetsu0422 commented on views/vwLearner/dailyTest.hbs
> +                // Do something with the response data
r ko do sth hả ô

2023-04-17 05:16 UTC, mugetsu0422 commented on views/vwLearner/dailyTest.hbs
> +                                // if (word[i] === guess && blanks[i] !== guess) {
ko dùng thì xóa ô

2023-04-17 05:16 UTC, mugetsu0422 commented on views/vwLearner/topicTest.hbs
> +            console.log(listAnswer.length)
xóa log

2023-04-17 05:16 UTC, mugetsu0422 commented on views/vwLearner/topicTestFinish.hbs
> +            $(document).ready(function () {
sao 2 hàm y chang lồng nhau v

2023-04-17 06:42 UTC, Dutus244 commented on package.json
> +    "bootstrap-icons": "^1.10.4",
tại nó không chạy ông nên npm luôn

2023-04-17 06:43 UTC, Dutus244 commented on views/vwLearner/dailyTest.hbs
> +                // Do something with the response data
không ông cái end của cái daily test thì chỉ trở về trang home thôi chứ việc submit kết quả nó ở từng từ rồi

2023-04-17 08:31 UTC, quytrungg commented on routes/learner.route.js
> +  const topicid = userAnswers.topicid
```suggestion
  const {topicid} = userAnswers
```

2023-04-17 08:33 UTC, quytrungg commented on routes/learner.route.js
> +    }
dùng `map` đi ông

2023-04-17 08:34 UTC, quytrungg commented on routes/learner.route.js
> +  const {wordID,check} = req.query;
```suggestion
  const {wordID, check} = req.query;
```

2023-04-17 08:34 UTC, quytrungg commented on routes/learner.route.js
> +  await learnerService.updateMemoryLevel(userID,wordID,check)
```suggestion
  await learnerService.updateMemoryLevel(userID, wordID, check)
```

2023-04-17 08:35 UTC, quytrungg commented on routes/learner.route.js
> +  await learnerService.updateMemoryLevel(userID,wordID,check)
cài [eslint](https://eslint.org/) đi ông

2023-04-17 08:36 UTC, quytrungg commented on services/learner.service.js
> +        }
này cũng nên dùng map

2023-04-17 08:37 UTC, quytrungg commented on services/learner.service.js
> +                    result[0].OptionD,
chỗ này ông có thể tạo 1 biến gán `result[0]` vào vì nó được dùng nhiều lần mà mỗi lần ông truy cập vào mảng thì hong được tối ưu lắm

2023-04-17 08:38 UTC, quytrungg commented on services/learner.service.js
> +                    result[0].OptionD,
hoặc có thể tạo thể làm như này: ```const {OptionA, OptionB, OptionC, OptionD} = result[0];

2023-04-17 08:39 UTC, quytrungg commented on services/learner.service.js
> +                    result[0].OptionD,
xong rồi ```const options = [OptionA, OptionB, OptionC, OptionD];```

2023-04-17 08:41 UTC, quytrungg commented on services/learner.service.js
> +                    OptionD: shuffledOptions[3],
xong rồi khúc này ông dùng spread cho cái mảng ở `options` ở comment trên

2023-04-17 08:41 UTC, quytrungg commented on services/learner.service.js
> +            'from topics'
tạo 1 biến `const query` để chứa cái raw query vào nhìn cho gọn hơn ông

2023-04-17 08:42 UTC, quytrungg commented on services/learner.service.js
> +        }
😄 viết vòng lặp đi ông

2023-04-17 08:43 UTC, quytrungg commented on services/learner.service.js
> +                    }
```suggestion
                    if (randomType2 == 1) {
                        const meaning = await db('words')
                            .select('wordmeaning')
                            .where('wordid', word.WordID);
                        question.Question = meaning[0].wordmeaning
                    }
```

2023-04-17 08:43 UTC, quytrungg commented on services/learner.service.js
> +                question.QuestionAvatar = tempquestion[0].QuestionAvatar
chỗ nào truy cập mảng nhiều lần cứ tách ra biến riêng cho gọn nha ông

2023-04-17 08:45 UTC, quytrungg commented on services/learner.service.js
logic trong này có cách nào tối ưu không tại nó dài quá 😭

2023-04-17 08:45 UTC, quytrungg requested changes
🚑

2023-04-17 09:32 UTC, mugetsu0422 commented on routes/learner.route.js
> +    userid: "6a6e7163-c669-480c-a28a-980246b50b98",
.userid ô

2023-04-18 10:10 UTC, Dutus244 commented on services/learner.service.js
> +            'from topics'
code này không phải của tui ông
=(

2023-04-18 10:14 UTC, Dutus244 commented on services/learner.service.js
> +        }
không ông, câu sql khác nhau mà =(

2023-04-18 10:15 UTC, Dutus244 commented on services/learner.service.js
> +                    OptionD: shuffledOptions[3],
spread là sao ông

2023-04-18 10:16 UTC, Dutus244 commented on routes/learner.route.js
> +    }
rồi ông

2023-04-18 10:16 UTC, Dutus244 commented on routes/learner.route.js
> +  const {wordID,check} = req.query;
oke ông

2023-04-18 10:16 UTC, Dutus244 commented on routes/learner.route.js
> +  await learnerService.updateMemoryLevel(userID,wordID,check)
hmm để cài ông

2023-04-18 10:16 UTC, Dutus244 commented on services/learner.service.js
> +                    result[0].OptionD,
oke luôn

2023-04-19 00:37 UTC, mugetsu0422 commented on services/learner.service.js
> +                    OptionD: shuffledOptions[3],
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax](đây ô)

2023-04-19 00:43 UTC, mugetsu0422 approved these changes

2023-04-19 09:53 UTC, ntny19 approved these changes

2023-04-19 10:51 UTC, merged