AT-change-category-to-lesson
Dutus244/TKPM-Project pull request #30
Opened 2023-04-20 10:25 UTC by annthu872

2023-04-21 18:22 UTC, quytrungg commented on routes/learner.route.js
>    }))
```suggestion
  lessonsProgress = lessonsProgress.map(lesson => {
    lessonname: lesson.lessonname,
    percentage: (lesson.wordshaslearned / lesson.totalwords) * 100,
  })
```

2023-04-21 18:23 UTC, quytrungg commented on routes/learner.route.js
>    }))
biến đặt là `it` ai hiểu được nó là gì 😢

2023-04-21 18:25 UTC, quytrungg requested changes
🆗

2023-04-21 18:31 UTC, quytrungg approved these changes

2023-04-22 00:45 UTC, mugetsu0422 approved these changes

2023-04-22 00:50 UTC, merged