feature/nhu y addlesson
Dutus244/TKPM-Project pull request #32
Opened 2023-04-21 15:16 UTC by ntny19

2023-04-21 18:16 UTC, HuynhNguyen0811 commented on services/admin.service.js
> +    async addtopic(entity){
đặt tên :(

2023-04-21 18:19 UTC, HuynhNguyen0811 commented on views/vwAdmin/addlesson.hbs
> +<main>
dòng trống :((

2023-04-21 18:23 UTC, HuynhNguyen0811 approved these changes

2023-04-21 18:27 UTC, quytrungg commented on routes/admin.route.js
> +
sao khúc này trống dị 😭

2023-04-21 18:28 UTC, quytrungg commented on routes/admin.route.js
>          topicid: topicid,
```suggestion
        topicid,
```

2023-04-21 18:28 UTC, quytrungg commented on routes/admin.route.js
>      // console.log(topiclist);
console.log này vẫn chưa xóa dị

2023-04-21 18:30 UTC, quytrungg approved these changes

2023-04-22 00:49 UTC, mugetsu0422 requested changes

2023-04-22 00:49 UTC, mugetsu0422 commented on views/vwAdmin/addquestion.hbs
> +            alert('Please input question')
```suggestion
            alert('Please input question')
            return
```

2023-04-22 00:49 UTC, mugetsu0422 commented on views/vwAdmin/addquestion.hbs
> +            alert('Please input question')
sao ở đây ko return mà ớ dưới thì return v

2023-04-22 13:30 UTC, ntny19 commented on routes/admin.route.js
>      // console.log(topiclist);
Không phải tui làm :(((

2023-04-22 14:27 UTC, mugetsu0422 approved these changes
💯

2023-04-22 14:47 UTC, merged