CN admin responsive
Dutus244/TKPM-Project pull request #59
Opened 2023-04-25 15:21 UTC by HuynhNguyen0811

2023-04-25 15:43 UTC, mugetsu0422 approved these changes
trùm

2023-04-25 15:57 UTC, quytrungg commented on views/vwAdmin/lessonlist.hbs
> +    //don't show table if there is no lesson
```suggestion
    // don't show table if there is no lesson
```

2023-04-25 15:57 UTC, quytrungg commented on views/vwAdmin/lessonlist.hbs
> +    //don't show table if there is no lesson
convention :Đ

2023-04-25 15:57 UTC, quytrungg commented on views/vwAdmin/lessonlist.hbs
> +    //add button
```suggestion
    // add button
```

2023-04-25 16:00 UTC, quytrungg requested changes
🚑 🆘 console log

2023-04-25 16:05 UTC, mugetsu0422 requested changes
Bỏ sót cái bc :( ẩu quá :(

2023-04-26 01:08 UTC, mugetsu0422 requested changes

2023-04-26 01:08 UTC, mugetsu0422 commented on public/img/background/edit_icon.png
bootstrap icon có icon bút chì mà ô, tải này về chi nặng repo :(

2023-04-26 01:08 UTC, mugetsu0422 commented on public/img/background/edit_icon.png
[đây](https://icons.getbootstrap.com/icons/pencil/)

2023-04-26 01:08 UTC, mugetsu0422 commented on views/vwAdmin/topicdetail.hbs
> +      <img class="icon" src="../../public/img/background/edit_icon.png"></img>
```suggestion
      <i class="icon bi bi-pencil"></i>
```
lý do như trên

2023-04-26 09:04 UTC, mugetsu0422 approved these changes

2023-04-26 10:15 UTC, quytrungg commented on views/vwAdmin/topicdetail.hbs
> +          console.log(error);
```suggestion
          console.error(error);
```

2023-04-26 10:16 UTC, quytrungg commented on views/vwAdmin/topicdetail.hbs
> +      // Send an AJAX request to update the topic name
```suggestion
      // send an AJAX request to update the topic name
```

2023-04-26 10:16 UTC, quytrungg commented on views/vwAdmin/topicdetail.hbs
> +      // Send an AJAX request to update the topic name
convention 😕

2023-04-26 10:18 UTC, quytrungg approved these changes
có thể fix các comment cho chuẩn quy tắc nếu có thời gian
right:
```// this is a correct comment```
wrong:
```
//comment
//Comment
// Comment
```

2023-04-26 10:21 UTC, HuynhNguyen0811 commented on views/vwAdmin/topicdetail.hbs
> +      // Send an AJAX request to update the topic name
:(

2023-04-26 10:22 UTC, merged