Feature/ny editquestion
Dutus244/TKPM-Project pull request #73
Opened 2023-04-27 15:51 UTC by ntny19

2023-04-27 16:17 UTC, mugetsu0422 requested changes

2023-04-27 17:50 UTC, quytrungg commented on routes/admin.route.js
> +    const question = questioninfo.question
destructuring đi bạn

2023-04-27 17:51 UTC, quytrungg commented on routes/admin.route.js
> +    const question = questioninfo.question
chỗ này nữa

2023-04-27 17:53 UTC, quytrungg approved these changes

2023-04-28 16:01 UTC, mugetsu0422 approved these changes

2023-04-28 16:02 UTC, merged